import { describe, expect, it } from "vitest";

import {
  ARGON2ID_PARAMETERS,
  GVDV_MAGIC,
  GVDV_TEXT_PREFIX,
  base64ToBytes,
  bytesToBase64,
  decryptBytes,
  decryptText,
  encryptBytes,
  encryptText,
  parseVaultPackage,
  type VaultAlgorithm,
} from "./crypto";

const password = "correct horse battery staple";
const rustAesFixture =
  "R1ZEVjEKAAAAxXsidmVyc2lvbiI6MSwiYWxnb3JpdGhtIjoiYWVzLTI1Ni1nY20iLCJrZGYiOiJhcmdvbjJpZC1kZWZhdWx0Iiwic2FsdF9iNjQiOiJBQUVDQXdRRkJnY0lDUW9MREEwT0R3PT0iLCJub25jZV9iNjQiOiJFQkVTRXhRVkZoY1lHUm9iIiwib3JpZ2luYWxfbmFtZSI6InJ1c3QtZml4dHVyZS50eHQiLCJvcmlnaW5hbF9taW1lIjoidGV4dC9wbGFpbiJ9UW6ivh39M5kTp56gOz+ttwIV9+kFSZvNZnKGEo6XGdJY4d98XYxGimEfCS785q28";

describe("GVDV1 crypto", () => {
  it("roundtrips the Rust-compatible AES text envelope", async () => {
    const plaintext = "Private hello, with Unicode: café 🔐";
    const payload = await encryptText(plaintext, password);

    expect(payload.startsWith(GVDV_TEXT_PREFIX)).toBe(true);
    expect(await decryptText(payload, password)).toBe(plaintext);

    const packageBytes = base64ToBytes(payload.slice(GVDV_TEXT_PREFIX.length));
    const parsed = parseVaultPackage(packageBytes);
    expect(parsed.header).toMatchObject({
      version: 1,
      algorithm: "aes-256-gcm",
      kdf: "argon2id-default",
      original_name: "encrypted-text.txt",
      original_mime: "text/plain",
    });
    expect(base64ToBytes(parsed.header.salt_b64)).toHaveLength(16);
    expect(base64ToBytes(parsed.header.nonce_b64)).toHaveLength(12);
  });

  it.each<VaultAlgorithm>(["aes-256-gcm", "chacha20-poly1305"])(
    "roundtrips bytes and metadata with %s",
    async (algorithm) => {
      const plaintext = new Uint8Array([0, 1, 2, 127, 128, 254, 255]);
      const metadata = {
        originalName: "evidence.bin",
        originalMime: "application/octet-stream",
      };

      const packageBytes = await encryptBytes(plaintext, password, metadata, algorithm);
      const decrypted = await decryptBytes(packageBytes, password);

      expect(decrypted.bytes).toEqual(plaintext);
      expect(decrypted.metadata).toEqual(metadata);
      expect(decrypted.header.algorithm).toBe(algorithm);
    },
  );

  it("writes the magic and four-byte big-endian JSON header length", async () => {
    const packageBytes = await encryptBytes(
      new Uint8Array([42]),
      password,
      { originalName: "answer.dat", originalMime: "application/octet-stream" },
    );
    const magic = new TextEncoder().encode(GVDV_MAGIC);

    expect(packageBytes.slice(0, magic.length)).toEqual(magic);
    const headerLength = new DataView(
      packageBytes.buffer,
      packageBytes.byteOffset + magic.length,
      4,
    ).getUint32(0, false);
    const parsed = parseVaultPackage(packageBytes);

    expect(headerLength).toBe(new TextEncoder().encode(JSON.stringify(parsed.header)).length);
    expect(parsed.ciphertext.length).toBe(1 + 16);
    expect(ARGON2ID_PARAMETERS).toEqual({
      memorySizeKiB: 19_456,
      iterations: 2,
      parallelism: 1,
      version: 0x13,
      keyLength: 32,
    });
  });

  it("decrypts a package generated by the desktop Rust implementation", async () => {
    const decrypted = await decryptBytes(base64ToBytes(rustAesFixture), "fixture-password");

    expect(new TextDecoder().decode(decrypted.bytes)).toBe(
      "Rust to browser interoperability",
    );
    expect(decrypted.metadata).toEqual({
      originalName: "rust-fixture.txt",
      originalMime: "text/plain",
    });
  });

  it("uses canonical standard base64", () => {
    const bytes = new Uint8Array([0xfb, 0xff, 0xef, 0x00]);
    const encoded = bytesToBase64(bytes);

    expect(encoded).toBe("+//vAA==");
    expect(base64ToBytes(encoded)).toEqual(bytes);
    expect(() => base64ToBytes("-_8=")).toThrow(/standard base64/i);
  });
});
